/**
 * @file TestClientSimDevicePipeline.cpp
 * @brief 公开规格仿真设备到客户端逐 bin QC 处理链的生产尺寸回归。
 */
#include "lidar_client/FrameProcessor.hpp"
#include "lidar_server/SimDevice.hpp"

#include <algorithm>
#include <cmath>
#include <iostream>
#include <optional>
#include <stdexcept>
#include <string>

namespace {

void require(bool condition, const std::string& message) {
    if (!condition) throw std::runtime_error(message);
}

bool contains_flag(const std::vector<std::string>& flags, const std::string& expected) {
    return std::find(flags.begin(), flags.end(), expected) != flags.end();
}

} // namespace

int main() {
    try {
        lidar_server::SimDeviceConfig device_config;
        device_config.enforce_public_spec = false;
        device_config.scan.include_vertical_stare = false;
        device_config.scan.azimuth_step_deg = 360.0;
        device_config.scan.scan_overhead_s = 0.0;
        device_config.stream.emit_camera_frames = false;
        device_config.stream.emit_product_frames = false;
        lidar_server::SimDevice device(device_config);

        lidar_client::FrameProcessor processor;
        std::optional<lidar_client::StepResult> completed;
        processor.set_step_complete_callback([&](lidar_client::StepResult result) {
            completed = std::move(result);
        });
        const auto frames = device.produce_scan_cycle(0);
        for (const auto& frame : frames) processor.handle_frame(frame);
        processor.finalize_step();

        require(completed.has_value(), "Explicit cycle boundary should close the client cycle");
        require(completed->processed_profiles.size() == 1,
                "Single-ray production-size scan should yield one processed profile");
        const auto& profile = completed->processed_profiles.front();
        require(profile.profile.ranges_m.size() == 5334
                    && profile.bin_quality.size() == 5334,
                "Production range axis and quality mask should remain aligned");
        require(completed->valid_bin_count > 0 && completed->masked_bin_count > 0,
                "Realistic signal should contain both usable and quality-masked bins");
        require(contains_flag(completed->qc_flags, "dead-time-correction-applied")
                    && contains_flag(completed->qc_flags, "afterpulse-correction-applied"),
                "Client should invert detector effects generated by the simulator");
        require(contains_flag(
                    completed->qc_flags,
                    "receiver-calibration-assumed-not-device-verified"),
                "Public-spec receiver assumptions must remain visible in end-to-end output");
        require(std::any_of(
                    profile.dry_extinction.begin(), profile.dry_extinction.end(),
                    [](double value) { return std::isfinite(value); }),
                "A valid contiguous range should survive through optical inversion");
        require(profile.pm25.empty() && profile.pm10.empty() && !completed->pm_calibrated,
                "Public-spec assumptions must not silently produce quantitative PM");

        std::cout << "SimDevice to FrameProcessor production-size assertions passed.\n";
        return 0;
    } catch (const std::exception& error) {
        std::cerr << error.what() << "\n";
        return 1;
    }
}
